//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mill5C.View.Window.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Mill5C.View.Window.Settings.CutterRendererType CutterRendererType {
            get {
                return ((global::Mill5C.View.Window.Settings.CutterRendererType)(this["CutterRendererType"]));
            }
            set {
                this["CutterRendererType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PostSimulation")]
        public global::Mill5C.View.Window.Settings.MaterialRendererType MaterialRendererType {
            get {
                return ((global::Mill5C.View.Window.Settings.MaterialRendererType)(this["MaterialRendererType"]));
            }
            set {
                this["MaterialRendererType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Mill5C.View.Window.Settings.PathRendererType PathRendererType {
            get {
                return ((global::Mill5C.View.Window.Settings.PathRendererType)(this["PathRendererType"]));
            }
            set {
                this["PathRendererType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaterialRendererDrawCubes {
            get {
                return ((bool)(this["MaterialRendererDrawCubes"]));
            }
            set {
                this["MaterialRendererDrawCubes"] = value;
            }
        }
    }
}
